=== ThomasFuser/Basic_Gym/data/schema.xsd
<?xml version="1.0" encoding="utf-8"?>



<xs:schema elementFormDefault="qualified"  xmlns:xs="http://www.w3.org/2001/XMLSchema">
/***********************************************/
//ABBONAMENTI DISPONIBILI NELLA PALESTRA
/*************************************************/

//Durata di un abbonamento
	<xs:simpleType name="durataT">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Abbonamento mensile"/>
			<xs:enumeration value="Abbonamento annuale"/>
		</xs:restriction>
	</xs:simpleType>

// Abbonamento
	<xs:complexType name="abbonamentoT">
		<xs:sequence>
			<xs:element name="durata" type="durataT"/>
			<xs:element name="prezzo" type="xs:decimal"/>
			<xs:element name="descrizione" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:string"/>
	</xs:complexType>
// Categoria: insieme di abbonamenti per Area Palestra (soft/cardio/cross)
	<xs:complexType name="categoriaT">
		<xs:sequence>
			<xs:element name="titolo" type="xs:string"/>
			<xs:element name="abbonamento" type="abbonamentoT" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
// Database di abbonamenti (tutte le categorie) disponibili agli utenti per l'acquisto
<xs:element name="listaAbbonamenti">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="categoria" type="categoriaT" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

/****************************************************/
//       ABBONAMENTO ACQUISTATO DA UN UTENTE
/********************************************************/

// tipo Abbonamento acquistato da un utente (utente loggato)

<xs:complexType name="abb_acquistatoT">
		<xs:sequence>
			<xs:element name="id_abbonamento" type="xs:string"/>
			<xs:element name="inizio" type="xs:date"/>
			<xs:element name="scadenza" type="xs:date"/>
		</xs:sequence>
</xs:complexType>


// tipo Lista degli abbonamenti acquistati da un utente (utente loggato)

<xs:complexType name="lista_acquistatiT">
		<xs:sequence>
			<xs:element name="abb_acquistato" type="abbacquistatoT"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
</xs:complexType>


/*************************************/
// TIPO DATI PERSONALI
/***************************************/
// tipo "numero di telefono"

<xs:simpleType name="telT">
	<xs:restriction base="xs:string">
		<xs:pattern value="[0-9]{9}"/>
	</xs:restriction>
</xs:simpleType>
// tipo "codice fiscale"

<xs:simpleType name="cfT">
	<xs:restriction base="xs:string">
		<xs:pattern value="[a-z]{6}[0-9]{2}[a-z][0-9]{2}[a-z][0-9]{3}[a-z]"/>
	</xs:restriction>
</xs:simpleType>

//genere 

<xs:simpleType name="genereT">
	<xs:restriction base="xs:string">
                <xs:enumeration value="Uomo"/>
		<xs:enumeration value="Donna"/>
	</xs:restriction>
</xs:simpleType>


//tipodati personali
<xs:complexType name="dati_personaliT">
		<xs:sequence>
			<xs:element name="nome" type="xs:string"/>
			<xs:element name="cognome" type="xs:string"/>
			<xs:element name="data_nascita" type="xs:date"/>
			<xs:element name="genere" type="genereT"/>
			<xs:element name="cf" type="cfT"/>
			<xs:element name="data_iscrizione" type="xs:date"/>
			<xs:element name="indirizzo" type="xs:string" minOccurs="0" />
			<xs:element name="citta" type="xs:string" minOccurs="0"/>
			<xs:element name="professione" type="xs:string" minOccurs="0"/>
			<xs:element name="tel" type="telT"/>
		</xs:sequence>
</xs:complexType>





/**********************************/
//TIPO DATI DI ACCESSO
/*************************************/
<complexType name="dati_accessoT">
	<xs:sequence>
		<xs:element name="mail" type="mailT"/>
		<xs:element name="password" type="passwordT"/>
	</xs:sequence>
</complexType>

// tipo email
<xs:simpleType name="mailT">
    <xs:restriction base="xs:string">
      	<xs:pattern value="[\w]*@[\w]*\.[com|it|org]"/>
    </xs:restriction>
 </xs:simpleType>

<xs:simpleType name="passwordT">
	 <xs:restriction base="xs:string">
      	<xs:pattern value="[\w]*"/>
		<xs:maxLength value="8"/>
    </xs:restriction>
 </xs:simpleType>

/***************************/
// TIPO CARTA DI CREDITO
/***************************/
//tipo della carta VISA/ MASTERCARD /AMERICAN EXPRESS
<xs:simpleType name="tipo_cartacreditoT">
	<xs:restriction base="xs:string">
		<xs:enumaration value="visa"/>
		<xs:enumeration value="mastercard"/>
		<xs:enumeration value="american express"/>
	</xs:restriction>
</xs:simpleType>
//numero carta

<xs:simpleType name="num_cartaT">
	<xs:restriction base="xs:string">
		<xs:pattern value="[0-9]{16}"/>
	</xs:restriction>
</xs:simpleType>

//tipo completo carta 
<xs:complexType name="cartacreditoT">
		<xs:sequence>
			<xs:element name="num_carta" type="num_cartaT"/>
			<xs:element name="tipo_carta" type="tipo_cartacreditoT"/>
			<xs:element name="scadenza" type="xs:date"/>
		</xs:sequence>
</xs:complexType>


/***************************/
// TIPO UTENTE 
/***************************/
<xs:element name="utente">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="dati_accesso" type="dati_accessoT"/>
			<xs:element name="dati_personali" type="dati_personaliT"/>
			<xs:element name="lista_acquistati" type="lista_acquistatiT"/>
			<xs:element name="dati_pagamento" type="cartacreditoT"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="admin">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="pw" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== ThomasFuser/Basic_Gym/data/prezzi.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaAbbonamenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema.xsd">
	<categoria>

		<titolo>Area Soft Fitness</titolo>
		<abbonamento ID="1" stato="valido">	
			<durata>Abbonamento mensile</durata>
			<prezzo>70</prezzo>
			<descrizione>Hai poco tempo per praticare sport? Con questo pacchetto lo sport si adatta alle tue esigenze! Vieni a trovarci subito! </descrizione>
			</abbonamento>
			<abbonamento ID="2" stato="valido">
			<durata>Abbonamento annuale</durata>
			<prezzo>650</prezzo>
			<descrizione>Accedi a tutti i corsi che desideri della nostra area Soft Fitness per 1 anno a un prezzo vantaggioso</descrizione>
		</abbonamento>
	    <abbonamento ID="3" stato="non-valido">
	    	<durata>Abbonamento mensile</durata>
	    <prezzo>80</prezzo>
	    <descrizione>Accedi a tutti i corsi che desideri della nostra area Soft Fitness per 1 mese a un prezzo vantaggioso</descrizione>
		</abbonamento>

	</categoria>

	<categoria>
		<titolo>Area Cardio Fitness</titolo>

		<abbonamento ID="4" stato="valido">
			<durata>Abbonamento mensile</durata>
			<prezzo>60</prezzo>
			<descrizione>Tutti i corsi di walking, spinning, total body per un'attivit√† aerobica a tutto tondo per 1 mese. </descrizione>
		</abbonamento>

    </categoria>
        
	<categoria>
		<titolo>Area Cross Fitness</titolo>
			
		<abbonamento ID="5" stato="valido"> 	
			<durata>Abbonamento mensile</durata>
			<prezzo>50</prezzo>
			<descrizione>Gli allenamenti brevi ma intensi sviluppano in breve tempo un fisico tonico e snello. Prova la nostra area Cross fitness per 1 mese</descrizione>
		</abbonamento>
		<abbonamento ID="6" stato="valido">
			<durata>Abbonamento annuale</durata>
			<prezzo>550</prezzo>
			<descrizione>Tutti i corsi senza alcun limite per 1 anno.</descrizione>
		</abbonamento>
		
	</categoria>
</listaAbbonamenti>
<!--note
 xmlns="http://www.prezzischema.it"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="prezzischema.xsd"-->
